url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jiayuan Daniel Yue" # the name of your site, e.g. ACME Corp.
description: "[t&#597;ja &#613;&#603;n &#613;e]"

include:
  - _blog